[build-system]
requires = [
    "setuptools>=80.3.1",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "planner"
version = "0.0.1"
description = "planner is an app built with SPLENT (https://www.splent.io)"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[project.optional-dependencies]
dev = [
    "watchdog",
    "locust",
]
core = [
    "splent_framework",
]

[tool.splent]
cli_version = "1.25.1"
features = [
    "splent-io/splent_feature_auth@v1.17.0",
    "splent-io/splent_feature_profile@v1.5.7",
    "splent-io/splent_feature_public@v1.7.3",
    "splent-io/splent_feature_session_filesystem@v1.1.1",
    "splent-io/splent_feature_settings@v0.4.0",
    "splent-io/splent_feature_theme@v0.12.1",
    "splent-io/splent_feature_calendars",
    "splent-io/splent_feature_tasks",
    "splent-io/splent_feature_calendar_view",
    "splent-io/splent_feature_quick_notes",
    "splent-io/splent_feature_calendar_sharing",
    "splent-io/splent_feature_signup@v0.1.0",
    "splent-io/splent_feature_auth_planner",
    "splent-io/splent_feature_signup_planner",
    "splent-io/splent_feature_profile_planner",
    "splent-io/splent_feature_task_recurrence",
]
features_dev = []
features_prod = []
spl = "planner_spl"

[tool.splent.layout]
base_template = "base_template.html"
hooks = [
    "layout.head.css",
    "calendars.nav",
    "layout.sidebar.top",
    "layout.anonymous_sidebar",
    "layout.authenticated_sidebar",
    "layout.sidebar.authenticated.items",
    "layout.navbar.anonymous",
    "layout.navbar.authenticated",
    "layout.footer",
    "layout.scripts",
]

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.packages.find]
where = [
    "src",
]
